// Tests for scripts/generate-nlm-contract.mjs (plan §2.3.1, §2.4).
//
// uv is injected. The real `uv pip compile` needs the network and several seconds; CI
// exercises it separately via the check:nlm-contract-generated step. What matters here is the
// logic around it: grammar enforcement, drift detection, and never writing during --check.

import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";

import {
  generateNlmContract,
  validateLockGrammar,
  requirementsWithoutHashes,
  sha256,
  MODES,
  BRIDGE_DIR,
  RUNTIME_LOCK,
  BUILD_LOCK,
  InputError,
  DriftError,
} from "../scripts/generate-nlm-contract.mjs";

const H1 = "a".repeat(64);
const H2 = "b".repeat(64);

const GOOD_LOCK = `# This file was autogenerated by uv via the following command:
#    uv pip compile pyproject.toml --python-version 3.12
anyio==4.11.0 \\
    --hash=sha256:${H1} \\
    --hash=sha256:${H2}
    # via notebooklm-mcp-cli
colorama==0.4.6 ; sys_platform == 'win32' \\
    --hash=sha256:${H1}
    # via click
`;

const BASE_OPTS = { root: "", uvVersion: "0.11.21", pythonVersion: "3.12", excludeNewer: "2026-07-16T00:00:00Z" };

/** A uv that writes canned content to whatever -o names, so no network is touched. */
function fakeUv(content = GOOD_LOCK) {
  const calls = [];
  return {
    calls,
    deps: {
      uvVersion: () => "0.11.21",
      runUv: (args, cwd) => {
        calls.push({ args, cwd });
        const out = args[args.indexOf("-o") + 1];
        const dest = path.join(cwd, out);
        fs.mkdirSync(path.dirname(dest), { recursive: true });
        fs.writeFileSync(dest, typeof content === "function" ? content(args) : content);
        return "";
      },
    },
  };
}

/** A bridge tree with pyproject + build input, optionally with locks already written. */
function withRoot(fn, { runtimeLock, buildLock } = {}) {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), "gnc-"));
  try {
    const bridge = path.join(root, BRIDGE_DIR);
    fs.mkdirSync(path.join(bridge, "requirements"), { recursive: true });
    fs.mkdirSync(path.join(bridge, "constraints"), { recursive: true });
    fs.writeFileSync(path.join(bridge, "pyproject.toml"), '[project]\nname="learn-kit-nlm-bridge"\n');
    fs.writeFileSync(path.join(bridge, "constraints/build-requirements.in"), "hatchling==1.27.0\n");
    if (runtimeLock !== undefined) fs.writeFileSync(path.join(bridge, RUNTIME_LOCK), runtimeLock);
    if (buildLock !== undefined) fs.writeFileSync(path.join(bridge, BUILD_LOCK), buildLock);
    return fn(root, bridge);
  } finally {
    fs.rmSync(root, { recursive: true, force: true });
  }
}

// ------------------------------------------------------------------ grammar
test("a canonical hashed lock passes the grammar", () => {
  assert.deepEqual(validateLockGrammar(GOOD_LOCK), []);
});

test("the grammar rejects every way of voiding --require-hashes", () => {
  const cases = {
    "index url": `--index-url https://example.test/simple\nanyio==4.11.0 \\\n    --hash=sha256:${H1}\n`,
    "extra index": `--extra-index-url https://evil.test/simple\nanyio==4.11.0 \\\n    --hash=sha256:${H1}\n`,
    "find links": `--find-links ./wheels\nanyio==4.11.0 \\\n    --hash=sha256:${H1}\n`,
    "editable": `-e ./src\n`,
    "requirements include": `-r other.txt\n`,
    "constraint include": `-c pins.txt\n`,
    "direct url": `anyio @ https://example.test/anyio.whl\n`,
    "direct file": `anyio @ file:///tmp/anyio.whl\n`,
    "bare name, unpinned": `anyio\n`,
    "range pin": `anyio>=4.0\n`,
  };
  for (const [label, text] of Object.entries(cases)) {
    assert.ok(validateLockGrammar(text).length > 0, `must reject: ${label}`);
  }
});

test("the grammar rejects a non-sha256 or malformed hash", () => {
  for (const bad of [
    `anyio==4.11.0 \\\n    --hash=md5:${"a".repeat(32)}\n`,
    `anyio==4.11.0 \\\n    --hash=sha256:${"a".repeat(63)}\n`,
    `anyio==4.11.0 \\\n    --hash=sha256:${H1.toUpperCase()}\n`,
  ]) {
    assert.ok(validateLockGrammar(bad).length > 0, `must reject: ${bad.split("\n")[1]}`);
  }
});

test("a PEP 508 marker on a pinned requirement is allowed", () => {
  assert.deepEqual(validateLockGrammar(`colorama==0.4.6 ; sys_platform == 'win32' \\\n    --hash=sha256:${H1}\n`), []);
});

test("requirementsWithoutHashes catches a pin carrying no hash", () => {
  assert.deepEqual(requirementsWithoutHashes(GOOD_LOCK), []);
  const naked = `anyio==4.11.0\ncolorama==0.4.6 \\\n    --hash=sha256:${H1}\n`;
  assert.deepEqual(requirementsWithoutHashes(naked), ["anyio==4.11.0"]);
});

test("sha256 is stable and content-sensitive", () => {
  assert.equal(sha256("abc"), sha256("abc"));
  assert.notEqual(sha256("abc"), sha256("abd"));
  assert.match(sha256("abc"), /^[0-9a-f]{64}$/);
});

// ------------------------------------------------------------------ argument validation
test("generateNlmContract validates its arguments", () => {
  withRoot((root) => {
    const { deps } = fakeUv();
    for (const bad of [
      { mode: "nope" },
      { mode: "runtime-lock", uvVersion: "0.11" },
      { mode: "runtime-lock", pythonVersion: "3" },
      { mode: "runtime-lock", excludeNewer: "2026-07-16" },
      { mode: "runtime-lock", excludeNewer: "now" },
      { mode: "runtime-lock", root: "" },
    ]) {
      assert.throws(() => generateNlmContract({ ...BASE_OPTS, root, ...bad }, deps), InputError, JSON.stringify(bad));
    }
  });
});

test("a uv other than the pinned one is a wrong-tooling error", () => {
  withRoot((root) => {
    const { deps } = fakeUv();
    const wrong = { ...deps, uvVersion: () => "0.12.0" };
    assert.throws(() => generateNlmContract({ ...BASE_OPTS, root, mode: "runtime-lock" }, wrong), InputError);
    const missing = { ...deps, uvVersion: () => null };
    assert.throws(() => generateNlmContract({ ...BASE_OPTS, root, mode: "runtime-lock" }, missing), InputError);
  });
});

test("all four modes are accepted names", () => {
  assert.deepEqual(MODES, ["runtime-lock", "build-lock", "snapshots", "all"]);
});

test("snapshots and all fail honestly while the bridge package is absent", () => {
  withRoot((root) => {
    const { deps } = fakeUv();
    for (const mode of ["snapshots", "all"]) {
      assert.throws(
        () => generateNlmContract({ ...BASE_OPTS, root, mode }, deps),
        (e) => e instanceof InputError && /do not exist yet/.test(e.message),
        mode,
      );
    }
  });
});

// ------------------------------------------------------------------ generation
test("generation writes the lock and reports its hash", () => {
  withRoot((root, bridge) => {
    const { deps, calls } = fakeUv();
    const r = generateNlmContract({ ...BASE_OPTS, root, mode: "runtime-lock" }, deps);
    assert.equal(r.changed, true);
    assert.equal(r.outputs.length, 1);
    assert.equal(r.outputs[0].sha256, sha256(GOOD_LOCK));
    assert.equal(fs.readFileSync(path.join(bridge, RUNTIME_LOCK), "utf8"), GOOD_LOCK);
    assert.equal(calls.length, 1);
  });
});

test("uv is invoked with relative paths only, so the recorded header is portable", () => {
  withRoot((root) => {
    const { deps, calls } = fakeUv();
    generateNlmContract({ ...BASE_OPTS, root, mode: "runtime-lock" }, deps);
    const args = calls[0].args;
    // The header uv writes is its own argv. An absolute path here would bake this machine
    // into the checked-in lock and make --check fail everywhere else.
    for (const a of args) {
      assert.ok(!path.isAbsolute(a), `argument must be relative: ${a}`);
      assert.ok(!/^[A-Za-z]:[\\/]/.test(a), `argument must not be a Windows absolute path: ${a}`);
    }
    assert.deepEqual(args.slice(0, 3), ["pip", "compile", "pyproject.toml"]);
    assert.ok(args.includes("--generate-hashes"));
    assert.ok(args.includes("--universal"));
    assert.ok(args.includes("--no-config"));
    assert.ok(args.includes("--no-sources"));
  });
});

test("regenerating identical content reports no change", () => {
  withRoot(
    (root) => {
      const { deps } = fakeUv();
      const r = generateNlmContract({ ...BASE_OPTS, root, mode: "runtime-lock" }, deps);
      assert.equal(r.changed, false);
    },
    { runtimeLock: GOOD_LOCK },
  );
});

test("a lock uv produces that breaks the grammar is refused, not written", () => {
  withRoot((root, bridge) => {
    const { deps } = fakeUv(`--index-url https://evil.test/simple\nanyio==4.11.0 \\\n    --hash=sha256:${H1}\n`);
    assert.throws(() => generateNlmContract({ ...BASE_OPTS, root, mode: "runtime-lock" }, deps), InputError);
    assert.equal(fs.existsSync(path.join(bridge, RUNTIME_LOCK)), false, "nothing may be written when the grammar fails");
  });
});

test("a lock with an unhashed pin is refused", () => {
  withRoot((root) => {
    const { deps } = fakeUv(`anyio==4.11.0\n`);
    assert.throws(
      () => generateNlmContract({ ...BASE_OPTS, root, mode: "runtime-lock" }, deps),
      (e) => e instanceof InputError && /no hashes/.test(e.message),
    );
  });
});

// ------------------------------------------------------------------ --check
test("--check passes when the checked-in lock matches", () => {
  withRoot(
    (root) => {
      const { deps } = fakeUv();
      const r = generateNlmContract({ ...BASE_OPTS, root, mode: "runtime-lock", check: true }, deps);
      assert.equal(r.changed, false);
    },
    { runtimeLock: GOOD_LOCK },
  );
});

test("--check fails on drift and never repairs it", () => {
  const stale = GOOD_LOCK.replace("4.11.0", "4.10.0");
  withRoot(
    (root, bridge) => {
      const { deps } = fakeUv();
      assert.throws(() => generateNlmContract({ ...BASE_OPTS, root, mode: "runtime-lock", check: true }, deps), DriftError);
      assert.equal(fs.readFileSync(path.join(bridge, RUNTIME_LOCK), "utf8"), stale, "--check must not write");
    },
    { runtimeLock: stale },
  );
});

test("--check fails when the lock is missing entirely", () => {
  withRoot((root, bridge) => {
    const { deps } = fakeUv();
    assert.throws(() => generateNlmContract({ ...BASE_OPTS, root, mode: "runtime-lock", check: true }, deps), DriftError);
    assert.equal(fs.existsSync(path.join(bridge, RUNTIME_LOCK)), false);
  });
});

test("--check leaves no temp directories behind", () => {
  const before = fs.readdirSync(os.tmpdir()).filter((d) => d.startsWith("nlm-contract-")).length;
  withRoot(
    (root) => {
      const { deps } = fakeUv();
      generateNlmContract({ ...BASE_OPTS, root, mode: "runtime-lock", check: true }, deps);
    },
    { runtimeLock: GOOD_LOCK },
  );
  const after = fs.readdirSync(os.tmpdir()).filter((d) => d.startsWith("nlm-contract-")).length;
  assert.equal(after, before);
});

test("build-lock targets its own input and output", () => {
  withRoot((root, bridge) => {
    const { deps, calls } = fakeUv();
    const r = generateNlmContract({ ...BASE_OPTS, root, mode: "build-lock" }, deps);
    assert.equal(calls[0].args[2], "constraints/build-requirements.in");
    assert.equal(r.outputs[0].path, `${BRIDGE_DIR}/${BUILD_LOCK}`);
    assert.ok(fs.existsSync(path.join(bridge, BUILD_LOCK)));
  });
});

test("a missing pyproject is an input error, not a crash", () => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), "gnc-empty-"));
  try {
    const { deps } = fakeUv();
    assert.throws(() => generateNlmContract({ ...BASE_OPTS, root, mode: "runtime-lock" }, deps), InputError);
  } finally {
    fs.rmSync(root, { recursive: true, force: true });
  }
});
