// Tests for scripts/generate-nlm-contract.mjs (plan §2.3.1, §2.4).
//
// uv is injected. The real `uv pip compile` needs the network and several seconds; CI
// exercises it separately via the check:nlm-contract-generated step. What matters here is the
// logic around it: grammar enforcement, drift detection, and never writing during --check.

import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";

import {
  generateNlmContract,
  validateLockGrammar,
  requirementsWithoutHashes,
  sha256,
  parseLock,
  canonicalJson,
  readPyprojectFacts,
  validatePublicPolicy,
  MODES,
  BRIDGE_DIR,
  RUNTIME_LOCK,
  BUILD_LOCK,
  PUBLIC_TOOLS,
  ENV_LOCK,
  DATA_DIR,
  SNAPSHOT_TOOL,
  InputError,
  DriftError,
} from "../scripts/generate-nlm-contract.mjs";

const REPO_ROOT = path.resolve(import.meta.dirname, "..");

const H1 = "a".repeat(64);
const H2 = "b".repeat(64);

const GOOD_LOCK = `# This file was autogenerated by uv via the following command:
#    uv pip compile pyproject.toml --python-version 3.12
anyio==4.11.0 \\
    --hash=sha256:${H1} \\
    --hash=sha256:${H2}
    # via notebooklm-mcp-cli
colorama==0.4.6 ; sys_platform == 'win32' \\
    --hash=sha256:${H1}
    # via click
`;

const BASE_OPTS = { root: "", uvVersion: "0.11.21", pythonVersion: "3.12", excludeNewer: "2026-07-16T00:00:00Z" };

/** A uv that writes canned content to whatever -o names, so no network is touched. */
function fakeUv(content = GOOD_LOCK) {
  const calls = [];
  return {
    calls,
    deps: {
      uvVersion: () => "0.11.21",
      runUv: (args, cwd) => {
        calls.push({ args, cwd });
        const out = args[args.indexOf("-o") + 1];
        const dest = path.join(cwd, out);
        fs.mkdirSync(path.dirname(dest), { recursive: true });
        fs.writeFileSync(dest, typeof content === "function" ? content(args) : content);
        return "";
      },
    },
  };
}

/** A bridge tree with pyproject + build input, optionally with locks already written. */
function withRoot(fn, { runtimeLock, buildLock } = {}) {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), "gnc-"));
  try {
    const bridge = path.join(root, BRIDGE_DIR);
    fs.mkdirSync(path.join(bridge, "requirements"), { recursive: true });
    fs.mkdirSync(path.join(bridge, "constraints"), { recursive: true });
    fs.writeFileSync(path.join(bridge, "pyproject.toml"), '[project]\nname="learn-kit-nlm-bridge"\n');
    fs.writeFileSync(path.join(bridge, "constraints/build-requirements.in"), "hatchling==1.27.0\n");
    if (runtimeLock !== undefined) fs.writeFileSync(path.join(bridge, RUNTIME_LOCK), runtimeLock);
    if (buildLock !== undefined) fs.writeFileSync(path.join(bridge, BUILD_LOCK), buildLock);
    return fn(root, bridge);
  } finally {
    fs.rmSync(root, { recursive: true, force: true });
  }
}

// ------------------------------------------------------------------ grammar
test("a canonical hashed lock passes the grammar", () => {
  assert.deepEqual(validateLockGrammar(GOOD_LOCK), []);
});

test("the grammar rejects every way of voiding --require-hashes", () => {
  const cases = {
    "index url": `--index-url https://example.test/simple\nanyio==4.11.0 \\\n    --hash=sha256:${H1}\n`,
    "extra index": `--extra-index-url https://evil.test/simple\nanyio==4.11.0 \\\n    --hash=sha256:${H1}\n`,
    "find links": `--find-links ./wheels\nanyio==4.11.0 \\\n    --hash=sha256:${H1}\n`,
    "editable": `-e ./src\n`,
    "requirements include": `-r other.txt\n`,
    "constraint include": `-c pins.txt\n`,
    "direct url": `anyio @ https://example.test/anyio.whl\n`,
    "direct file": `anyio @ file:///tmp/anyio.whl\n`,
    "bare name, unpinned": `anyio\n`,
    "range pin": `anyio>=4.0\n`,
  };
  for (const [label, text] of Object.entries(cases)) {
    assert.ok(validateLockGrammar(text).length > 0, `must reject: ${label}`);
  }
});

test("the grammar rejects a non-sha256 or malformed hash", () => {
  for (const bad of [
    `anyio==4.11.0 \\\n    --hash=md5:${"a".repeat(32)}\n`,
    `anyio==4.11.0 \\\n    --hash=sha256:${"a".repeat(63)}\n`,
    `anyio==4.11.0 \\\n    --hash=sha256:${H1.toUpperCase()}\n`,
  ]) {
    assert.ok(validateLockGrammar(bad).length > 0, `must reject: ${bad.split("\n")[1]}`);
  }
});

test("a PEP 508 marker on a pinned requirement is allowed", () => {
  assert.deepEqual(validateLockGrammar(`colorama==0.4.6 ; sys_platform == 'win32' \\\n    --hash=sha256:${H1}\n`), []);
});

test("requirementsWithoutHashes catches a pin carrying no hash", () => {
  assert.deepEqual(requirementsWithoutHashes(GOOD_LOCK), []);
  const naked = `anyio==4.11.0\ncolorama==0.4.6 \\\n    --hash=sha256:${H1}\n`;
  assert.deepEqual(requirementsWithoutHashes(naked), ["anyio==4.11.0"]);
});

test("sha256 is stable and content-sensitive", () => {
  assert.equal(sha256("abc"), sha256("abc"));
  assert.notEqual(sha256("abc"), sha256("abd"));
  assert.match(sha256("abc"), /^[0-9a-f]{64}$/);
});

// ------------------------------------------------------------------ argument validation
test("generateNlmContract validates its arguments", () => {
  withRoot((root) => {
    const { deps } = fakeUv();
    for (const bad of [
      { mode: "nope" },
      { mode: "runtime-lock", uvVersion: "0.11" },
      { mode: "runtime-lock", pythonVersion: "3" },
      { mode: "runtime-lock", excludeNewer: "2026-07-16" },
      { mode: "runtime-lock", excludeNewer: "now" },
      { mode: "runtime-lock", root: "" },
    ]) {
      assert.throws(() => generateNlmContract({ ...BASE_OPTS, root, ...bad }, deps), InputError, JSON.stringify(bad));
    }
  });
});

test("a uv other than the pinned one is a wrong-tooling error", () => {
  withRoot((root) => {
    const { deps } = fakeUv();
    const wrong = { ...deps, uvVersion: () => "0.12.0" };
    assert.throws(() => generateNlmContract({ ...BASE_OPTS, root, mode: "runtime-lock" }, wrong), InputError);
    const missing = { ...deps, uvVersion: () => null };
    assert.throws(() => generateNlmContract({ ...BASE_OPTS, root, mode: "runtime-lock" }, missing), InputError);
  });
});

test("all four modes are accepted names", () => {
  assert.deepEqual(MODES, ["runtime-lock", "build-lock", "snapshots", "all"]);
});

test("snapshots and all fail honestly when the fingerprinting tool is absent", () => {
  withRoot((root) => {
    const { deps } = fakeUv();
    for (const mode of ["snapshots", "all"]) {
      assert.throws(
        () => generateNlmContract({ ...BASE_OPTS, root, mode }, deps),
        (e) => e instanceof InputError && /does not exist yet/.test(e.message),
        mode,
      );
    }
  });
});

// ------------------------------------------------------------------ generation
test("generation writes the lock and reports its hash", () => {
  withRoot((root, bridge) => {
    const { deps, calls } = fakeUv();
    const r = generateNlmContract({ ...BASE_OPTS, root, mode: "runtime-lock" }, deps);
    assert.equal(r.changed, true);
    assert.equal(r.outputs.length, 1);
    assert.equal(r.outputs[0].sha256, sha256(GOOD_LOCK));
    assert.equal(fs.readFileSync(path.join(bridge, RUNTIME_LOCK), "utf8"), GOOD_LOCK);
    assert.equal(calls.length, 1);
  });
});

test("uv is invoked with relative paths only, so the recorded header is portable", () => {
  withRoot((root) => {
    const { deps, calls } = fakeUv();
    generateNlmContract({ ...BASE_OPTS, root, mode: "runtime-lock" }, deps);
    const args = calls[0].args;
    // The header uv writes is its own argv. An absolute path here would bake this machine
    // into the checked-in lock and make --check fail everywhere else.
    for (const a of args) {
      assert.ok(!path.isAbsolute(a), `argument must be relative: ${a}`);
      assert.ok(!/^[A-Za-z]:[\\/]/.test(a), `argument must not be a Windows absolute path: ${a}`);
    }
    assert.deepEqual(args.slice(0, 3), ["pip", "compile", "pyproject.toml"]);
    assert.ok(args.includes("--generate-hashes"));
    assert.ok(args.includes("--universal"));
    assert.ok(args.includes("--no-config"));
    assert.ok(args.includes("--no-sources"));
  });
});

test("regenerating identical content reports no change", () => {
  withRoot(
    (root) => {
      const { deps } = fakeUv();
      const r = generateNlmContract({ ...BASE_OPTS, root, mode: "runtime-lock" }, deps);
      assert.equal(r.changed, false);
    },
    { runtimeLock: GOOD_LOCK },
  );
});

test("a lock uv produces that breaks the grammar is refused, not written", () => {
  withRoot((root, bridge) => {
    const { deps } = fakeUv(`--index-url https://evil.test/simple\nanyio==4.11.0 \\\n    --hash=sha256:${H1}\n`);
    assert.throws(() => generateNlmContract({ ...BASE_OPTS, root, mode: "runtime-lock" }, deps), InputError);
    assert.equal(fs.existsSync(path.join(bridge, RUNTIME_LOCK)), false, "nothing may be written when the grammar fails");
  });
});

test("a lock with an unhashed pin is refused", () => {
  withRoot((root) => {
    const { deps } = fakeUv(`anyio==4.11.0\n`);
    assert.throws(
      () => generateNlmContract({ ...BASE_OPTS, root, mode: "runtime-lock" }, deps),
      (e) => e instanceof InputError && /no hashes/.test(e.message),
    );
  });
});

// ------------------------------------------------------------------ --check
test("--check passes when the checked-in lock matches", () => {
  withRoot(
    (root) => {
      const { deps } = fakeUv();
      const r = generateNlmContract({ ...BASE_OPTS, root, mode: "runtime-lock", check: true }, deps);
      assert.equal(r.changed, false);
    },
    { runtimeLock: GOOD_LOCK },
  );
});

test("--check fails on drift and never repairs it", () => {
  const stale = GOOD_LOCK.replace("4.11.0", "4.10.0");
  withRoot(
    (root, bridge) => {
      const { deps } = fakeUv();
      assert.throws(() => generateNlmContract({ ...BASE_OPTS, root, mode: "runtime-lock", check: true }, deps), DriftError);
      assert.equal(fs.readFileSync(path.join(bridge, RUNTIME_LOCK), "utf8"), stale, "--check must not write");
    },
    { runtimeLock: stale },
  );
});

test("--check fails when the lock is missing entirely", () => {
  withRoot((root, bridge) => {
    const { deps } = fakeUv();
    assert.throws(() => generateNlmContract({ ...BASE_OPTS, root, mode: "runtime-lock", check: true }, deps), DriftError);
    assert.equal(fs.existsSync(path.join(bridge, RUNTIME_LOCK)), false);
  });
});

test("--check leaves no temp directories behind", () => {
  const before = fs.readdirSync(os.tmpdir()).filter((d) => d.startsWith("nlm-contract-")).length;
  withRoot(
    (root) => {
      const { deps } = fakeUv();
      generateNlmContract({ ...BASE_OPTS, root, mode: "runtime-lock", check: true }, deps);
    },
    { runtimeLock: GOOD_LOCK },
  );
  const after = fs.readdirSync(os.tmpdir()).filter((d) => d.startsWith("nlm-contract-")).length;
  assert.equal(after, before);
});

test("build-lock targets its own input and output", () => {
  withRoot((root, bridge) => {
    const { deps, calls } = fakeUv();
    const r = generateNlmContract({ ...BASE_OPTS, root, mode: "build-lock" }, deps);
    assert.equal(calls[0].args[2], "constraints/build-requirements.in");
    assert.equal(r.outputs[0].path, `${BRIDGE_DIR}/${BUILD_LOCK}`);
    assert.ok(fs.existsSync(path.join(bridge, BUILD_LOCK)));
  });
});

test("a missing pyproject is an input error, not a crash", () => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), "gnc-empty-"));
  try {
    const { deps } = fakeUv();
    assert.throws(() => generateNlmContract({ ...BASE_OPTS, root, mode: "runtime-lock" }, deps), InputError);
  } finally {
    fs.rmSync(root, { recursive: true, force: true });
  }
});

// ------------------------------------------------------------------ lock parsing

test("parseLock recovers the closure, its markers and every hash", () => {
  const closure = parseLock(GOOD_LOCK);
  assert.deepEqual(closure, [
    { name: "anyio", version: "4.11.0", marker: null, hashes: [`sha256:${H1}`, `sha256:${H2}`] },
    { name: "colorama", version: "0.4.6", marker: "sys_platform == 'win32'", hashes: [`sha256:${H1}`] },
  ]);
});

test("parseLock ignores comments and the `# via` provenance trailers", () => {
  // Those trailers sit between a requirement and the next one; treating one as a requirement
  // would put a bogus entry in the environment lock.
  assert.equal(parseLock("# header\n\n    # via something\n").length, 0);
});

// ------------------------------------------------------------------ canonical JSON

test("canonicalJson sorts keys, escapes non-ASCII and ends with exactly one newline", () => {
  const out = canonicalJson({ b: 1, a: { d: "é中", c: 2 } });
  // The expected escape text is built from code points, so this expectation cannot be
  // silently weakened by a tool that rewrites backslash escapes.
  const esc = (s) => [...s].map((c) => "\\u" + c.charCodeAt(0).toString(16).padStart(4, "0")).join("");
  const expected = `{\n  "a": {\n    "c": 2,\n    "d": "${esc("é中")}"\n  },\n  "b": 1\n}\n`;
  assert.equal(out, expected);
  assert.ok(!/[^\x00-\x7f]/.test(out), "output must be pure ASCII");
  assert.ok(out.endsWith("}\n") && !out.endsWith("\n\n"));
});

test("canonicalJson is stable regardless of key insertion order", () => {
  // This is what makes --check meaningful: the same content must serialize to the same bytes.
  assert.equal(canonicalJson({ a: 1, b: 2 }), canonicalJson({ b: 2, a: 1 }));
});

// ------------------------------------------------------------------ pyproject facts

const GOOD_PYPROJECT = `[project]
name = "learn-kit-nlm-bridge"
version = "4.0.0"
requires-python = "==3.12.*"
dependencies = ["notebooklm-mcp-cli==0.8.7"]
`;

test("readPyprojectFacts reads the pinned facts rather than restating them", () => {
  assert.deepEqual(readPyprojectFacts(GOOD_PYPROJECT), {
    bridgeVersion: "4.0.0",
    connectorVersion: "0.8.7",
    requiresPython: "==3.12.*",
  });
});

test("a prose mention of [project.scripts] is not a declaration of one", () => {
  // Regression: the real pyproject.toml explains in a comment WHY it declares no
  // [project.scripts]. An unanchored match treated that comment as the section itself and
  // refused a perfectly good file.
  const withComment = `# NO [project.scripts] - deliberately, see the rationale above.\n${GOOD_PYPROJECT}`;
  assert.deepEqual(readPyprojectFacts(withComment).bridgeVersion, "4.0.0");
});

test("an actual [project.scripts] table is refused", () => {
  // Two distributions claiming `nlm` would let install order decide which one wins.
  assert.throws(
    () => readPyprojectFacts(`${GOOD_PYPROJECT}\n[project.scripts]\nnlm = "x:main"\n`),
    (e) => e instanceof InputError && /no \[project\.scripts\]/.test(e.message),
  );
});

test("a non-3.12 requires-python or a missing connector pin is refused", () => {
  assert.throws(() => readPyprojectFacts(GOOD_PYPROJECT.replace("==3.12.*", ">=3.12")), InputError);
  assert.throws(() => readPyprojectFacts(GOOD_PYPROJECT.replace('"notebooklm-mcp-cli==0.8.7"', '"notebooklm-mcp-cli"')), InputError);
});

// ------------------------------------------------------------------ public policy
//
// These use the REAL checked-in policy and the REAL upstream snapshot as fixtures, then
// mutate a clone. A hand-written fixture could drift from what ships; mutating the real one
// proves both that the shipped policy is valid and that the validator would actually catch a
// widening of it.

const readData = (name) =>
  JSON.parse(fs.readFileSync(path.join(REPO_ROOT, BRIDGE_DIR, DATA_DIR, name), "utf8"));
const realPolicy = () => JSON.parse(fs.readFileSync(path.join(REPO_ROOT, BRIDGE_DIR, PUBLIC_TOOLS), "utf8"));
const realUpstream = () => readData("upstream-tools-v0.8.7.json");

const toolOf = (p, name) => p.tools.find((t) => t.name === name);
const branchOf = (p, kind) =>
  toolOf(p, "studio_create").inputSchema.oneOf.find((b) => b.properties.artifact_type.const === kind);

test("the checked-in policy is a valid narrowing of the real upstream surface", () => {
  assert.deepEqual(validatePublicPolicy(realPolicy(), realUpstream()), []);
});

test("the checked-in policy exposes exactly the six agreed tools", () => {
  assert.deepEqual(
    realPolicy().tools.map((t) => t.name).sort(),
    ["notebook_create", "notebook_get", "notebook_list", "source_add", "studio_create", "studio_status"],
  );
});

test("every way of widening the policy is rejected", () => {
  const mutations = {
    "source_ids becomes optional": (p) => {
      const b = branchOf(p, "audio");
      b.required = b.required.filter((r) => r !== "source_ids");
    },
    "source_ids accepts an empty array": (p) => {
      // Python truthiness: an empty list is falsy, so upstream resolves it to every source.
      branchOf(p, "audio").properties.source_ids.minItems = 0;
    },
    "source_ids accepts more than three": (p) => {
      branchOf(p, "audio").properties.source_ids.maxItems = 99;
    },
    "source_ids allows duplicates": (p) => {
      branchOf(p, "video").properties.source_ids.uniqueItems = false;
    },
    "confirm is no longer literal true": (p) => {
      branchOf(p, "audio").properties.confirm = { type: "boolean" };
    },
    "mind_map accepts focus_prompt": (p) => {
      branchOf(p, "mind_map").properties.focus_prompt = { type: "string" };
    },
    "mind_map accepts language": (p) => {
      branchOf(p, "mind_map").properties.language = { type: "string" };
    },
    "video_style_prompt is exposed": (p) => {
      branchOf(p, "video").properties.video_style_prompt = { type: "string" };
    },
    "a studio_create branch is dropped": (p) => {
      toolOf(p, "studio_create").inputSchema.oneOf.pop();
    },
    "additionalProperties is reopened": (p) => {
      toolOf(p, "notebook_get").inputSchema.additionalProperties = true;
    },
    "a branch reopens additionalProperties": (p) => {
      branchOf(p, "slide_deck").additionalProperties = true;
    },
    "source_add regains a url source": (p) => {
      toolOf(p, "source_add").inputSchema.properties.url = { type: "string" };
    },
    "source_add regains pasted text": (p) => {
      toolOf(p, "source_add").inputSchema.properties.text = { type: "string" };
    },
    "source_type stops being const file": (p) => {
      toolOf(p, "source_add").inputSchema.properties.source_type = { type: "string" };
    },
    "wait stops being const true": (p) => {
      toolOf(p, "source_add").inputSchema.properties.wait = { type: "boolean" };
    },
    "studio_status exposes the rename surface": (p) => {
      toolOf(p, "studio_status").inputSchema.properties.action = { type: "string" };
    },
    "studio_status stops injecting status": (p) => {
      delete toolOf(p, "studio_status").upstream.inject.action;
    },
    "notebook_list takes an argument again": (p) => {
      toolOf(p, "notebook_list").inputSchema.properties.max_results = { type: "integer" };
    },
    "notebook_list injects a different cap": (p) => {
      toolOf(p, "notebook_list").upstream.inject.max_results = 999;
    },
    "notebook_create title becomes optional": (p) => {
      toolOf(p, "notebook_create").inputSchema.required = [];
    },
    "an extra tool is smuggled in": (p) => {
      p.tools.push({
        name: "source_delete",
        inputSchema: { type: "object", additionalProperties: false, properties: {} },
        upstream: { tool: "source_delete", inject: {} },
      });
    },
    "a property upstream does not have": (p) => {
      toolOf(p, "notebook_get").inputSchema.properties.evil = { type: "string" };
    },
    "an injected key upstream does not have": (p) => {
      toolOf(p, "notebook_get").upstream.inject = { evil: 1 };
    },
    "the policy version stops matching the filename": (p) => {
      p.policy_version = "v2";
    },
    // The inject map is forwarded to the connector verbatim, so a forbidden key smuggled into
    // it bypasses the advertised-schema checks. These widen through inject rather than props.
    "source_add smuggles a url through inject": (p) => {
      toolOf(p, "source_add").upstream.inject.url = "https://attacker.test/x";
    },
    "studio_status smuggles a rename target through inject": (p) => {
      toolOf(p, "studio_status").upstream.inject.new_title = "renamed";
    },
    "studio_create smuggles a video style prompt through inject": (p) => {
      toolOf(p, "studio_create").upstream.inject.video_style_prompt = "cinematic";
    },
  };

  const upstream = realUpstream();
  for (const [label, mutate] of Object.entries(mutations)) {
    const p = realPolicy();
    const before = JSON.stringify(p);
    mutate(p);
    // Guard against a mutation that silently does nothing: the test would then be asserting
    // about an unmodified fixture and would pass for the wrong reason.
    assert.notEqual(JSON.stringify(p), before, `mutation "${label}" did not change the policy`);
    const problems = validatePublicPolicy(p, upstream);
    assert.ok(problems.length > 0, `widening must be rejected: ${label}`);
  }
});

test("the validator's structural rules are each guarded by their own message", () => {
  // The mutation sweep above proves widenings are rejected, but it exercises the schema-shape
  // rules and skips several structural ones (format, oneOf placement, branch kinds, ...). Those
  // are asserted here by their SPECIFIC message, so a refactor that drops one is caught even
  // though the whole policy would still be "rejected" by some other rule.
  const upstream = realUpstream();
  const firesMessageContaining = (needle, mutate) => {
    const p = realPolicy();
    mutate(p);
    const problems = validatePublicPolicy(p, upstream);
    assert.ok(
      problems.some((m) => m.includes(needle)),
      `expected a problem containing ${JSON.stringify(needle)}, got: ${problems.join(" | ") || "<none>"}`,
    );
  };

  firesMessageContaining("format must be", (p) => {
    p.format = "something-else";
  });
  firesMessageContaining("format_version must be 1", (p) => {
    p.format_version = 2;
  });
  firesMessageContaining("tools must be an array", (p) => {
    p.tools = "not-an-array";
  });
  firesMessageContaining("inputSchema must be an object schema", (p) => {
    toolOf(p, "notebook_get").inputSchema = { type: "string" };
  });
  firesMessageContaining("only studio_create may use oneOf", (p) => {
    const g = toolOf(p, "notebook_get").inputSchema;
    g.oneOf = [{ type: "object", additionalProperties: false, properties: {} }];
  });
  firesMessageContaining("branches must be const", (p) => {
    // Keep all four branches so the length check passes and the kind check is what fires.
    branchOf(p, "audio").properties.artifact_type.const = "infographic";
  });
  firesMessageContaining("focus_prompt must be a string", (p) => {
    branchOf(p, "video").properties.focus_prompt = { type: "integer" };
  });
});

test("a policy naming a tool upstream does not advertise is rejected", () => {
  const p = realPolicy();
  toolOf(p, "notebook_get").upstream.tool = "notebook_delete";
  assert.ok(validatePublicPolicy(p, realUpstream()).some((m) => /not a tool upstream advertises/.test(m)));
});

test("the auth guard snapshot pins every symbol the runner relies on", () => {
  const guard = readData("upstream-auth-guard-v0.8.7.json");
  const byName = Object.fromEntries(guard.symbols.map((s) => [`${s.module}.${s.qualname}`, s]));
  // The method that is swapped out, the disk-only helper the replacement calls, and both
  // headless-auth entry points that must never run.
  assert.ok(byName["notebooklm_tools.core.base.BaseClient._try_reload_or_headless_auth"]);
  assert.ok(byName["notebooklm_tools.core.auth.load_cached_tokens"]);
  assert.ok(byName["notebooklm_tools.utils.auth_browser.run_headless_auth"]);
  assert.ok(byName["notebooklm_tools.utils.cdp.run_headless_auth"]);
  for (const s of guard.symbols) {
    assert.match(s.source_sha256, /^[0-9a-f]{64}$/, `${s.qualname} needs a real source hash`);
    assert.ok(["replaced", "sentinel", "depended_on"].includes(s.role));
  }
});

test("the environment lock records a hashed closure and no exact Python patch", () => {
  const env = readData("environment-lock.json");
  assert.equal(env.python_requires, "==3.12.*");
  // An exact patch here would make this checked-in file fail --check on any machine whose
  // 3.12.x differs - which is exactly what the Windows/Ubuntu matrix guarantees.
  assert.ok(!/"3\.12\.\d+"/.test(JSON.stringify(env)), "must not pin an exact 3.12.x patch");
  assert.equal(env.closure.length, env.closure_count);
  assert.ok(env.closure.length > 50);
  for (const r of env.closure) {
    assert.ok(r.hashes.length > 0, `${r.name} must carry hashes`);
    for (const h of r.hashes) assert.match(h, /^sha256:[0-9a-f]{64}$/);
  }
  assert.ok(env.closure.some((r) => r.name === "notebooklm-mcp-cli" && r.version === "0.8.7"));
  // hatchling builds the wheel; it has no business in the runtime environment.
  assert.ok(!env.closure.some((r) => r.name === "hatchling"), "build-only closure must stay out");
  for (const cmd of Object.values(env.replay)) {
    for (const a of cmd) assert.ok(!path.isAbsolute(a), `replay argv must stay portable: ${a}`);
  }
});

test("the checked-in _data files are byte-clean: LF, no BOM, one trailing newline", () => {
  // These bytes are hashed into the Gate fingerprint and shipped in the wheel. A CRLF
  // checkout would change every hash, so .gitattributes pins LF and this asserts it held.
  for (const name of [
    "public-tools-v1.json",
    "upstream-tools-v0.8.7.json",
    "upstream-auth-guard-v0.8.7.json",
    "environment-lock.json",
  ]) {
    const raw = fs.readFileSync(path.join(REPO_ROOT, BRIDGE_DIR, DATA_DIR, name));
    assert.ok(!raw.includes(0x0d), `${name} must contain no CR bytes`);
    assert.notEqual(raw[0], 0xef, `${name} must not start with a BOM`);
    const text = raw.toString("utf8");
    assert.ok(text.endsWith("\n") && !text.endsWith("\n\n"), `${name} needs exactly one trailing newline`);
  }
});

// ------------------------------------------------------------------ snapshots mode
//
// uv and the Python fingerprinter are injected: the real ones need a network install and a
// couple of minutes, and CI exercises them through check:nlm-contract-generated. What is
// worth testing here is everything around them — that the locks are read rather than assumed,
// that the policy is validated against upstream, and that --check never writes.

const SNAP_PYPROJECT = `[project]
name = "learn-kit-nlm-bridge"
version = "4.0.0"
requires-python = "==3.12.*"
dependencies = ["notebooklm-mcp-cli==0.8.7"]
`;

const SNAP_RUNTIME_LOCK = `# autogenerated
notebooklm-mcp-cli==0.8.7 \\
    --hash=sha256:${H1}
colorama==0.4.6 ; sys_platform == 'win32' \\
    --hash=sha256:${H2}
`;

const SNAP_BUILD_LOCK = `# autogenerated
hatchling==1.27.0 \\
    --hash=sha256:${H1}
`;

/** A bridge fixture complete enough for snapshots: locks, policy, and the tool file. */
function withSnapshotBridge(fn, { policyText, pyproject = SNAP_PYPROJECT } = {}) {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), "gnc-snap-"));
  try {
    const bridge = path.join(root, BRIDGE_DIR);
    for (const d of ["requirements", "constraints", "tools", DATA_DIR]) {
      fs.mkdirSync(path.join(bridge, d), { recursive: true });
    }
    fs.writeFileSync(path.join(bridge, "pyproject.toml"), pyproject);
    fs.writeFileSync(path.join(bridge, "constraints/build-requirements.in"), "hatchling==1.27.0\n");
    fs.writeFileSync(path.join(bridge, RUNTIME_LOCK), SNAP_RUNTIME_LOCK);
    fs.writeFileSync(path.join(bridge, BUILD_LOCK), SNAP_BUILD_LOCK);
    fs.writeFileSync(path.join(bridge, SNAPSHOT_TOOL), "# fingerprinter (injected in tests)\n");
    fs.writeFileSync(
      path.join(bridge, PUBLIC_TOOLS),
      policyText ?? fs.readFileSync(path.join(REPO_ROOT, BRIDGE_DIR, PUBLIC_TOOLS), "utf8"),
    );
    return fn(root, bridge);
  } finally {
    fs.rmSync(root, { recursive: true, force: true });
  }
}

/** uv + the Python fingerprinter, faked. The fingerprinter emits the real checked-in bytes. */
function snapshotDeps({ pythonVersion = "3.12.13", upstreamText, guardText } = {}) {
  const calls = [];
  const dataDir = path.join(REPO_ROOT, BRIDGE_DIR, DATA_DIR);
  const upstream = upstreamText ?? fs.readFileSync(path.join(dataDir, "upstream-tools-v0.8.7.json"), "utf8");
  const guard = guardText ?? fs.readFileSync(path.join(dataDir, "upstream-auth-guard-v0.8.7.json"), "utf8");
  return {
    calls,
    deps: {
      uvVersion: () => "0.11.21",
      runUv: (args, cwd) => {
        calls.push({ cmd: "uv", args, cwd });
        if (args[0] === "pip" && args[1] === "compile") {
          const out = args[args.indexOf("-o") + 1];
          const dest = path.join(cwd, out);
          fs.mkdirSync(path.dirname(dest), { recursive: true });
          fs.writeFileSync(dest, out === RUNTIME_LOCK ? SNAP_RUNTIME_LOCK : SNAP_BUILD_LOCK);
        }
        return "";
      },
      runPython: (exe, args, cwd) => {
        calls.push({ cmd: "python", exe, args, cwd });
        const out = args[args.indexOf("--out") + 1];
        fs.mkdirSync(out, { recursive: true });
        fs.writeFileSync(path.join(out, "upstream-tools-v0.8.7.json"), upstream);
        fs.writeFileSync(path.join(out, "upstream-auth-guard-v0.8.7.json"), guard);
        return `${JSON.stringify({ connector_version: "0.8.7", python_version: pythonVersion, outputs: [] })}\n`;
      },
    },
  };
}

test("snapshots writes the two fingerprints and the environment lock", () => {
  withSnapshotBridge((root, bridge) => {
    const { deps } = snapshotDeps();
    const r = generateNlmContract({ ...BASE_OPTS, root, mode: "snapshots" }, deps);
    assert.deepEqual(
      r.outputs.map((o) => o.path.split("/").pop()),
      ["upstream-tools-v0.8.7.json", "upstream-auth-guard-v0.8.7.json", "environment-lock.json"],
    );
    assert.equal(r.changed, true);
    const env = JSON.parse(fs.readFileSync(path.join(bridge, ENV_LOCK), "utf8"));
    assert.equal(env.bridge_version, "4.0.0");
    assert.equal(env.connector_version, "0.8.7");
    assert.equal(env.locks.runtime.sha256, sha256(SNAP_RUNTIME_LOCK));
    assert.equal(env.locks.build.sha256, sha256(SNAP_BUILD_LOCK));
    assert.deepEqual(env.closure.map((c) => c.name), ["notebooklm-mcp-cli", "colorama"]);
  });
});

test("snapshots never rewrites the hand-written policy", () => {
  withSnapshotBridge((root, bridge) => {
    const before = fs.readFileSync(path.join(bridge, PUBLIC_TOOLS), "utf8");
    generateNlmContract({ ...BASE_OPTS, root, mode: "snapshots" }, snapshotDeps().deps);
    // The policy is the one file a human owns: the generator may validate and hash it, but
    // widening must always be a reviewed edit, never a generated one.
    assert.equal(fs.readFileSync(path.join(bridge, PUBLIC_TOOLS), "utf8"), before);
  });
});

test("the throwaway venv is installed from the lock with hashes enforced", () => {
  withSnapshotBridge((root) => {
    const { deps, calls } = snapshotDeps();
    generateNlmContract({ ...BASE_OPTS, root, mode: "snapshots" }, deps);
    const venv = calls.find((c) => c.cmd === "uv" && c.args[0] === "venv");
    assert.ok(venv, "a throwaway venv must be created");
    assert.ok(venv.args.includes("--no-python-downloads"), "must not silently download a Python");
    assert.ok(venv.args.includes("--no-config"));
    const install = calls.find((c) => c.cmd === "uv" && c.args[0] === "pip" && c.args[1] === "install");
    assert.ok(install.args.includes("--require-hashes"), "the whole point of the lock");
    assert.ok(install.args.includes("--no-build"), "wheels only: no sdist may execute code");
    assert.ok(install.args.includes("--no-config"));
    assert.ok(install.args.some((a) => a.endsWith("notebooklm-mcp-cli-0.8.7-py312.lock.txt")));
  });
});

test("the fingerprinter is told which connector version to expect", () => {
  withSnapshotBridge((root) => {
    const { deps, calls } = snapshotDeps();
    generateNlmContract({ ...BASE_OPTS, root, mode: "snapshots" }, deps);
    const py = calls.find((c) => c.cmd === "python");
    // Taken from pyproject, not hardcoded here, so the pin has one source.
    assert.deepEqual(py.args.slice(-2), ["--connector-version", "0.8.7"]);
    assert.ok(py.args[0].endsWith("generate_contract_snapshots.py"));
  });
});

test("a venv that is not Python 3.12 is refused", () => {
  withSnapshotBridge((root) => {
    const { deps } = snapshotDeps({ pythonVersion: "3.13.1" });
    assert.throws(
      () => generateNlmContract({ ...BASE_OPTS, root, mode: "snapshots" }, deps),
      (e) => e instanceof InputError && /Python 3\.12/.test(e.message),
    );
  });
});

test("a pyproject whose pin disagrees with the lock is refused", () => {
  // If these two ever diverge, the fingerprint would describe a different release from the
  // one the installer actually installs.
  const mismatched = SNAP_PYPROJECT.replace("0.8.7", "0.8.8");
  withSnapshotBridge(
    (root) => {
      assert.throws(
        () => generateNlmContract({ ...BASE_OPTS, root, mode: "snapshots" }, snapshotDeps().deps),
        (e) => e instanceof InputError && /but the runtime lock resolves/.test(e.message),
      );
    },
    { pyproject: mismatched },
  );
});

test("snapshots refuses a policy that widens the surface, and writes nothing", () => {
  const widened = JSON.parse(fs.readFileSync(path.join(REPO_ROOT, BRIDGE_DIR, PUBLIC_TOOLS), "utf8"));
  widened.tools.find((t) => t.name === "source_add").inputSchema.properties.url = { type: "string" };
  withSnapshotBridge(
    (root, bridge) => {
      assert.throws(
        () => generateNlmContract({ ...BASE_OPTS, root, mode: "snapshots" }, snapshotDeps().deps),
        (e) => e instanceof InputError && /minimal-permission policy/.test(e.message),
      );
      assert.ok(!fs.existsSync(path.join(bridge, ENV_LOCK)), "a refused run must leave no environment lock");
    },
    { policyText: `${JSON.stringify(widened, null, 2)}\n` },
  );
});

test("a policy with CRLF is refused rather than silently rehashed", () => {
  // The bytes are the contract. A CRLF checkout would change the hash the Gate binds.
  const crlf = fs.readFileSync(path.join(REPO_ROOT, BRIDGE_DIR, PUBLIC_TOOLS), "utf8").replace(/\n/g, "\r\n");
  withSnapshotBridge(
    (root) => {
      assert.throws(
        () => generateNlmContract({ ...BASE_OPTS, root, mode: "snapshots" }, snapshotDeps().deps),
        (e) => e instanceof InputError && /LF only/.test(e.message),
      );
    },
    { policyText: crlf },
  );
});

test("snapshots --check passes when the checked-in files match", () => {
  withSnapshotBridge((root) => {
    const { deps } = snapshotDeps();
    generateNlmContract({ ...BASE_OPTS, root, mode: "snapshots" }, deps);
    const r = generateNlmContract({ ...BASE_OPTS, root, mode: "snapshots", check: true }, deps);
    assert.equal(r.changed, false);
  });
});

test("snapshots --check fails on drift and never repairs it", () => {
  withSnapshotBridge((root, bridge) => {
    const { deps } = snapshotDeps();
    generateNlmContract({ ...BASE_OPTS, root, mode: "snapshots" }, deps);
    const tampered = `${fs.readFileSync(path.join(bridge, ENV_LOCK), "utf8")}\n`;
    fs.writeFileSync(path.join(bridge, ENV_LOCK), tampered);
    assert.throws(
      () => generateNlmContract({ ...BASE_OPTS, root, mode: "snapshots", check: true }, deps),
      DriftError,
    );
    assert.equal(fs.readFileSync(path.join(bridge, ENV_LOCK), "utf8"), tampered, "--check must not write");
  });
});

test("snapshots --check fails when a snapshot is missing entirely", () => {
  withSnapshotBridge((root) => {
    assert.throws(
      () => generateNlmContract({ ...BASE_OPTS, root, mode: "snapshots", check: true }, snapshotDeps().deps),
      (e) => e instanceof DriftError && /does not exist/.test(e.message),
    );
  });
});

test("snapshots leaves no temp directories behind", () => {
  withSnapshotBridge((root) => {
    const before = fs.readdirSync(os.tmpdir()).filter((d) => d.startsWith("nlm-snapshots-")).length;
    generateNlmContract({ ...BASE_OPTS, root, mode: "snapshots" }, snapshotDeps().deps);
    const after = fs.readdirSync(os.tmpdir()).filter((d) => d.startsWith("nlm-snapshots-")).length;
    assert.equal(after, before);
  });
});

test("all runs the locks before the snapshots that read them", () => {
  withSnapshotBridge((root) => {
    const { deps, calls } = snapshotDeps();
    const r = generateNlmContract({ ...BASE_OPTS, root, mode: "all" }, deps);
    assert.deepEqual(r.outputs.map((o) => o.path.split("/").pop()), [
      "notebooklm-mcp-cli-0.8.7-py312.lock.txt",
      "build-hatchling-1.27.0-py312.txt",
      "upstream-tools-v0.8.7.json",
      "upstream-auth-guard-v0.8.7.json",
      "environment-lock.json",
    ]);
    // Ordering is load-bearing: snapshots installs from the runtime lock and records both lock
    // hashes, so it must observe the freshly written files, not the previous generation.
    const compileIdx = calls.findIndex((c) => c.args[0] === "pip" && c.args[1] === "compile");
    const installIdx = calls.findIndex((c) => c.args[0] === "pip" && c.args[1] === "install");
    // >= 0 first: findIndex returns -1 when a call is absent, and `-1 < installIdx` is true, so
    // a bare `compileIdx < installIdx` would also pass if the locks were never compiled — the
    // exact stale-lock failure this test exists to catch.
    assert.ok(compileIdx >= 0, "the locks must actually be compiled");
    assert.ok(installIdx >= 0, "the snapshot venv must actually install");
    assert.ok(compileIdx < installIdx, "locks must be compiled before the snapshot venv installs");
  });
});
